-- MySQL Script generated by MySQL Workbench
-- Monday, 14 August, 2017 06:10:46 PM PHT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema visionin_international
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema visionin_international
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `visionin_international` DEFAULT CHARACTER SET utf8 ;
USE `visionin_international` ;

-- -----------------------------------------------------
-- Table `visionin_international`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `visionin_international`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` VARCHAR(45) NOT NULL,
  `remember_token` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `visionin_international`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `visionin_international`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `article` LONGTEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  `created_by` INT NOT NULL,
  PRIMARY KEY (`id`, `created_by`),
  INDEX `fk_news_users_idx` (`created_by` ASC),
  CONSTRAINT `fk_news_users`
    FOREIGN KEY (`created_by`)
    REFERENCES `visionin_international`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `visionin_international`.`testimonials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `visionin_international`.`testimonials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `organization` VARCHAR(255) NULL,
  `testimony` MEDIUMTEXT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  `created_by` INT NOT NULL,
  PRIMARY KEY (`id`, `created_by`),
  INDEX `fk_testimonials_users1_idx` (`created_by` ASC),
  CONSTRAINT `fk_testimonials_users1`
    FOREIGN KEY (`created_by`)
    REFERENCES `visionin_international`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `visionin_international`.`programs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `visionin_international`.`programs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `created_by` INT NOT NULL,
  `deleted_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`, `created_by`),
  INDEX `fk_programs_users1_idx` (`created_by` ASC),
  CONSTRAINT `fk_programs_users1`
    FOREIGN KEY (`created_by`)
    REFERENCES `visionin_international`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `visionin_international`.`opportunities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `visionin_international`.`opportunities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `position` VARCHAR(255) NOT NULL,
  `company` VARCHAR(255) NOT NULL,
  `company_website` VARCHAR(255) NOT NULL,
  `company_email` VARCHAR(255) NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `duration` VARCHAR(255) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `interview_date` DATE NULL,
  `stipend` INT NULL,
  `stipend_currency` VARCHAR(255) NULL,
  `housing_information` VARCHAR(255) NULL,
  `local_transport` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `created_by` INT NOT NULL,
  `deleted_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `programs_id` INT NOT NULL,
  PRIMARY KEY (`id`, `created_by`, `programs_id`),
  INDEX `fk_opportunities_programs1_idx` (`programs_id` ASC),
  INDEX `fk_opportunities_users1_idx` (`created_by` ASC),
  CONSTRAINT `fk_opportunities_programs1`
    FOREIGN KEY (`programs_id`)
    REFERENCES `visionin_international`.`programs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_opportunities_users1`
    FOREIGN KEY (`created_by`)
    REFERENCES `visionin_international`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
